sudo: required
dist: trusty
language: cpp

addons:
  apt:
    packages:
      - libarchive-dev
      - libpugixml-dev

script:
  - autoreconf -fi
  - ./configure --enable-zhfst || { cat config.log && exit 1; }
  - make -j3
  - make -j1 check
